FROM ubuntu:16.04

RUN apt-get update && apt-get install -y doxygen graphviz

COPY doc /radiant-node/doc
COPY src /radiant-node/src

WORKDIR /radiant-node

RUN doxygen doc/Doxyfile

FROM nginx:alpine

COPY --from=0 /radiant-node/doc/doxygen/html /usr/share/nginx/html
