

#include <QtGlobal>

// Automatically generated by extract_strings_qt.py
#ifdef __GNUC__
#define UNUSED __attribute__((unused))
#else
#define UNUSED
#endif
static const char UNUSED *bitcoin_strings[] = {
QT_TRANSLATE_NOOP("radiant-node", "The %s developers"),
QT_TRANSLATE_NOOP("radiant-node", ""
"-maxtxfee is set very high! Fees this large could be paid on a single "
"transaction."),
QT_TRANSLATE_NOOP("radiant-node", ""
"Can't generate a change-address key. Private keys are disabled for this "
"wallet."),
QT_TRANSLATE_NOOP("radiant-node", ""
"Cannot obtain a lock on data directory %s. %s is probably already running."),
QT_TRANSLATE_NOOP("radiant-node", ""
"Cannot provide specific connections and have addrman find outgoing "
"connections at the same time."),
QT_TRANSLATE_NOOP("radiant-node", ""
"Cannot upgrade a non HD split wallet without upgrading to support pre split "
"keypool. Please use -upgradewallet=200300 or -upgradewallet with no version "
"specified."),
QT_TRANSLATE_NOOP("radiant-node", ""
"Distributed under the MIT software license, see the accompanying file %s or "
"%s"),
QT_TRANSLATE_NOOP("radiant-node", ""
"Error reading %s! All keys read correctly, but transaction data or address "
"book entries might be missing or incorrect."),
QT_TRANSLATE_NOOP("radiant-node", ""
"Error: Listening for incoming connections failed (listen returned error %s)"),
QT_TRANSLATE_NOOP("radiant-node", ""
"Invalid amount for -maxtxfee=<amount>: '%s' (must be at least the minrelay "
"fee of %s to prevent stuck transactions)"),
QT_TRANSLATE_NOOP("radiant-node", ""
"Max generated block size (blockmaxsize) cannot exceed the excessive block "
"size (excessiveblocksize)"),
QT_TRANSLATE_NOOP("radiant-node", ""
"Please check that your computer's date and time are correct! If your clock "
"is wrong, %s will not work properly."),
QT_TRANSLATE_NOOP("radiant-node", ""
"Please contribute if you find %s useful. Visit %s for further information "
"about the software."),
QT_TRANSLATE_NOOP("radiant-node", ""
"Prune configured below the minimum of %d MiB.  Please use a higher number."),
QT_TRANSLATE_NOOP("radiant-node", ""
"Prune: last wallet synchronisation goes beyond pruned data. You need to -"
"reindex (download the whole blockchain again in case of pruned node)"),
QT_TRANSLATE_NOOP("radiant-node", ""
"Rescans are not possible in pruned mode. You will need to use -reindex which "
"will download the whole blockchain again."),
QT_TRANSLATE_NOOP("radiant-node", ""
"The block database contains a block which appears to be from the future. "
"This may be due to your computer's date and time being set incorrectly. Only "
"rebuild the block database if you are sure that your computer's date and "
"time are correct"),
QT_TRANSLATE_NOOP("radiant-node", ""
"The transaction amount is too small to send after the fee has been deducted"),
QT_TRANSLATE_NOOP("radiant-node", ""
"This is a pre-release test build - use at your own risk - do not use for "
"mining or merchant applications"),
QT_TRANSLATE_NOOP("radiant-node", ""
"This is the transaction fee you may pay when fee estimates are not available."),
QT_TRANSLATE_NOOP("radiant-node", ""
"This product includes software developed by the OpenSSL Project for use in "
"the OpenSSL Toolkit %s and cryptographic software written by Eric Young and "
"UPnP software written by Thomas Bernard."),
QT_TRANSLATE_NOOP("radiant-node", ""
"Total length of network version string (%i) exceeds maximum length (%i). "
"Reduce the number or size of uacomments."),
QT_TRANSLATE_NOOP("radiant-node", ""
"Transaction broadcast interval must not be configured with a negative value."),
QT_TRANSLATE_NOOP("radiant-node", ""
"Transaction broadcast rate must not be configured with a negative value."),
QT_TRANSLATE_NOOP("radiant-node", ""
"Unable to replay blocks. You will need to rebuild the database using -"
"reindex-chainstate."),
QT_TRANSLATE_NOOP("radiant-node", ""
"Warning: Private keys detected in wallet {%s} with disabled private keys"),
QT_TRANSLATE_NOOP("radiant-node", ""
"Warning: The network does not appear to fully agree! Some miners appear to "
"be experiencing issues."),
QT_TRANSLATE_NOOP("radiant-node", ""
"Warning: This version of %s is old and may fall out of network consensus in "
"%d day(s). Please upgrade, or add expire=0 to your configuration file if you "
"want to continue running this version. If you do nothing, the software will "
"gracefully degrade by limiting its functionality in %d day(s)."),
QT_TRANSLATE_NOOP("radiant-node", ""
"Warning: This version of %s is old and may have fallen out of network "
"consensus %d day(s) ago. Please upgrade, or add expire=0 to your "
"configuration file."),
QT_TRANSLATE_NOOP("radiant-node", ""
"Warning: Wallet file corrupt, data salvaged! Original %s saved as %s in %s; "
"if your balance or transactions are incorrect you should restore from a "
"backup."),
QT_TRANSLATE_NOOP("radiant-node", ""
"Warning: We do not appear to fully agree with our peers! You may need to "
"upgrade, or other nodes may need to upgrade."),
QT_TRANSLATE_NOOP("radiant-node", ""
"You need to rebuild the database using -reindex to go back to unpruned "
"mode.  This will redownload the entire blockchain"),
QT_TRANSLATE_NOOP("radiant-node", "%s corrupt, salvage failed"),
QT_TRANSLATE_NOOP("radiant-node", "%s is set very high!"),
QT_TRANSLATE_NOOP("radiant-node", "(press q to shutdown and continue later)"),
QT_TRANSLATE_NOOP("radiant-node", "-maxmempool must be at least %d MB"),
QT_TRANSLATE_NOOP("radiant-node", "Cannot downgrade wallet"),
QT_TRANSLATE_NOOP("radiant-node", "Cannot resolve -%s address: '%s'"),
QT_TRANSLATE_NOOP("radiant-node", "Cannot write to data directory '%s'; check permissions."),
QT_TRANSLATE_NOOP("radiant-node", "Change index out of range"),
QT_TRANSLATE_NOOP("radiant-node", "Config setting for %s only applied on %s network when in [%s] section."),
QT_TRANSLATE_NOOP("radiant-node", "Copyright (C) %i-%i"),
QT_TRANSLATE_NOOP("radiant-node", "Corrupted block database detected"),
QT_TRANSLATE_NOOP("radiant-node", "Do you want to rebuild the block database now?"),
QT_TRANSLATE_NOOP("radiant-node", "Done loading"),
QT_TRANSLATE_NOOP("radiant-node", "Error initializing block database"),
QT_TRANSLATE_NOOP("radiant-node", "Error initializing wallet database environment %s!"),
QT_TRANSLATE_NOOP("radiant-node", "Error loading %s"),
QT_TRANSLATE_NOOP("radiant-node", "Error loading %s: Private keys can only be disabled during creation"),
QT_TRANSLATE_NOOP("radiant-node", "Error loading %s: Wallet corrupted"),
QT_TRANSLATE_NOOP("radiant-node", "Error loading %s: Wallet requires newer version of %s"),
QT_TRANSLATE_NOOP("radiant-node", "Error loading block database"),
QT_TRANSLATE_NOOP("radiant-node", "Error loading wallet %s. Duplicate -wallet filename specified."),
QT_TRANSLATE_NOOP("radiant-node", "Error opening block database"),
QT_TRANSLATE_NOOP("radiant-node", "Error reading from database, shutting down."),
QT_TRANSLATE_NOOP("radiant-node", "Error upgrading chainstate database"),
QT_TRANSLATE_NOOP("radiant-node", "Error"),
QT_TRANSLATE_NOOP("radiant-node", "Error: A fatal internal error occurred, see debug.log for details"),
QT_TRANSLATE_NOOP("radiant-node", "Error: Disk space is low for %s"),
QT_TRANSLATE_NOOP("radiant-node", "Error: Disk space is low!"),
QT_TRANSLATE_NOOP("radiant-node", "Excessive block size must be > 1,000,000 bytes (1MB)"),
QT_TRANSLATE_NOOP("radiant-node", "Failed to listen on any port. Use -listen=0 if you want this."),
QT_TRANSLATE_NOOP("radiant-node", "Failed to rescan the wallet during initialization"),
QT_TRANSLATE_NOOP("radiant-node", "Importing..."),
QT_TRANSLATE_NOOP("radiant-node", "Incorrect or no genesis block found. Wrong datadir for network?"),
QT_TRANSLATE_NOOP("radiant-node", "Information"),
QT_TRANSLATE_NOOP("radiant-node", "Initialization sanity check failed. %s is shutting down."),
QT_TRANSLATE_NOOP("radiant-node", "Insufficient funds"),
QT_TRANSLATE_NOOP("radiant-node", "Invalid -onion address or hostname: '%s'"),
QT_TRANSLATE_NOOP("radiant-node", "Invalid -proxy address or hostname: '%s'"),
QT_TRANSLATE_NOOP("radiant-node", "Invalid P2P permission: '%s'"),
QT_TRANSLATE_NOOP("radiant-node", "Invalid amount for -%s=<amount>: '%s'"),
QT_TRANSLATE_NOOP("radiant-node", "Invalid amount for -fallbackfee=<amount>: '%s'"),
QT_TRANSLATE_NOOP("radiant-node", "Invalid amount for -paytxfee=<amount>: '%s' (must be at least %s)"),
QT_TRANSLATE_NOOP("radiant-node", "Invalid coin selection hint"),
QT_TRANSLATE_NOOP("radiant-node", "Invalid netmask specified in -whitelist: '%s'"),
QT_TRANSLATE_NOOP("radiant-node", "Keypool ran out, please call keypoolrefill first"),
QT_TRANSLATE_NOOP("radiant-node", "Loading P2P addresses..."),
QT_TRANSLATE_NOOP("radiant-node", "Loading banlist..."),
QT_TRANSLATE_NOOP("radiant-node", "Loading block index..."),
QT_TRANSLATE_NOOP("radiant-node", "Loading wallet..."),
QT_TRANSLATE_NOOP("radiant-node", "Need to specify a port with -whitebind: '%s'"),
QT_TRANSLATE_NOOP("radiant-node", "Not enough file descriptors available."),
QT_TRANSLATE_NOOP("radiant-node", "Prune cannot be configured with a negative value."),
QT_TRANSLATE_NOOP("radiant-node", "Prune mode is incompatible with -txindex."),
QT_TRANSLATE_NOOP("radiant-node", "Pruning blockstore..."),
QT_TRANSLATE_NOOP("radiant-node", "Reducing -maxconnections from %d to %d, because of system limitations."),
QT_TRANSLATE_NOOP("radiant-node", "Replaying blocks..."),
QT_TRANSLATE_NOOP("radiant-node", "Rescanning..."),
QT_TRANSLATE_NOOP("radiant-node", "Section [%s] is not recognized."),
QT_TRANSLATE_NOOP("radiant-node", "Signing transaction failed"),
QT_TRANSLATE_NOOP("radiant-node", "Specified -walletdir \"%s\" does not exist"),
QT_TRANSLATE_NOOP("radiant-node", "Specified -walletdir \"%s\" is a relative path"),
QT_TRANSLATE_NOOP("radiant-node", "Specified -walletdir \"%s\" is not a directory"),
QT_TRANSLATE_NOOP("radiant-node", "Specified blocks directory \"%s\" does not exist."),
QT_TRANSLATE_NOOP("radiant-node", "Specified index directory \"%s\" does not exist."),
QT_TRANSLATE_NOOP("radiant-node", "Specify data directory"),
QT_TRANSLATE_NOOP("radiant-node", "Starting network threads..."),
QT_TRANSLATE_NOOP("radiant-node", "The source code is available from %s."),
QT_TRANSLATE_NOOP("radiant-node", "The specified config file %s does not exist"),
QT_TRANSLATE_NOOP("radiant-node", "The transaction amount is too small to pay the fee"),
QT_TRANSLATE_NOOP("radiant-node", "The wallet will avoid paying less than the minimum relay fee."),
QT_TRANSLATE_NOOP("radiant-node", "This is the minimum transaction fee you pay on every transaction."),
QT_TRANSLATE_NOOP("radiant-node", "This is the transaction fee you will pay if you send a transaction."),
QT_TRANSLATE_NOOP("radiant-node", "Transaction amount too small"),
QT_TRANSLATE_NOOP("radiant-node", "Transaction amounts must not be negative"),
QT_TRANSLATE_NOOP("radiant-node", "Transaction fee and change calculation failed"),
QT_TRANSLATE_NOOP("radiant-node", "Transaction has too long of a mempool chain"),
QT_TRANSLATE_NOOP("radiant-node", "Transaction must have at least one recipient"),
QT_TRANSLATE_NOOP("radiant-node", "Transaction too large for fee policy"),
QT_TRANSLATE_NOOP("radiant-node", "Transaction too large"),
QT_TRANSLATE_NOOP("radiant-node", "Unable to bind to %s on this computer (bind returned error %s)"),
QT_TRANSLATE_NOOP("radiant-node", "Unable to bind to %s on this computer. %s is probably already running."),
QT_TRANSLATE_NOOP("radiant-node", "Unable to create the PID file '%s': %s"),
QT_TRANSLATE_NOOP("radiant-node", "Unable to generate initial keys"),
QT_TRANSLATE_NOOP("radiant-node", "Unable to generate keys"),
QT_TRANSLATE_NOOP("radiant-node", "Unable to start HTTP server. See debug log for details."),
QT_TRANSLATE_NOOP("radiant-node", "Unknown network specified in -onlynet: '%s'"),
QT_TRANSLATE_NOOP("radiant-node", "Unsupported logging category %s=%s."),
QT_TRANSLATE_NOOP("radiant-node", "Upgrading UTXO database"),
QT_TRANSLATE_NOOP("radiant-node", "Upgrading txindex database"),
QT_TRANSLATE_NOOP("radiant-node", "User Agent comment (%s) contains unsafe characters."),
QT_TRANSLATE_NOOP("radiant-node", "Using %s."),
QT_TRANSLATE_NOOP("radiant-node", "Verifying blocks..."),
QT_TRANSLATE_NOOP("radiant-node", "Verifying wallet..."),
QT_TRANSLATE_NOOP("radiant-node", "Verifying wallets..."),
QT_TRANSLATE_NOOP("radiant-node", "Wallet %s resides outside wallet directory %s"),
QT_TRANSLATE_NOOP("radiant-node", "Wallet needed to be rewritten: restart %s to complete"),
QT_TRANSLATE_NOOP("radiant-node", "Warning"),
QT_TRANSLATE_NOOP("radiant-node", "Zapping all transactions from wallet..."),
QT_TRANSLATE_NOOP("radiant-node", "press q to shutdown"),
};
